version = 1

test_patterns = ["test/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"

[[transformers]]
name = "google-java-format"
enabled = true